version: '3.7'
services:
  app:
    container_name: fast_api
    build: 
      context: ./
      dockerfile: ./docker/fastapi/Dockerfile
    ports:
      - "5080:80"
    networks:
      - docker-shared-services
      - net
    volumes:
      - ./app:/app
    environment:
      FASTAPI_ENV: development
    depends_on:
        - mysql

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    container_name: fastapi_db
    environment:
      - MYSQL_ROOT_PASSWORD=fastapi
      - MYSQL_DATABASE=fastapi_db
    ports:
      - "3315:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - net

networks:
  docker-shared-services:
    external: true
  net:
    driver: bridge